const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const root=path.join(process.env.PGENRO_PROJECT_ROOT?path.resolve(process.env.PGENRO_PROJECT_ROOT):path.resolve(__dirname,'../..'),'admin');
const baseMock=fs.readFileSync(path.join(__dirname,'mock.js'),'utf8').replace("Promise.resolve().then(()=>{","Promise.resolve().then(async()=>{if(window.__latency)await new Promise(r=>setTimeout(r,window.__latency));").replace("return {data:result.slice(q.lo,q.hi+1)","localStorage.setItem('__test_db',JSON.stringify(window.__db));return {data:result.slice(q.lo,q.hi+1)");
const readers=process.env.PGENRO_READERS_ROOT||path.join(__dirname,'node_modules');
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname;const f=path.join(root,name);if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404);return res.end('Not found');}res.setHeader('Content-Type',({'.css':'text/css','.html':'text/html','.js':'text/javascript'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});
const findings=[],errors=[];let browser;
function fixture(){const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;window.__db.office_memos=Array.from({length:24},(_,i)=>{const month=new Date(now.getFullYear(),now.getMonth()-i%6,1);return {id:'memo'+i,memoNo:`MEMO-2026-${String(i+1).padStart(3,'0')}`,date:`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-01`,addressedTo:'All Division Heads',subject:i%2?'Field inspection and reporting':'Submission of monthly work plans',issuedBy:'Provincial ENRO',remarks:'For review',isPinned:i<2,pdfUrl:i%2?'data:text/plain;base64,TWVtbw==':'',pdfFileName:i%2?'memo-fixture.txt':''};});window.__db.communications=[];window.__db.profiles=[];}
async function context(wrapped=false){
 const c=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Manila',acceptDownloads:true});
 await c.route('**/*',async route=>{
  const url=route.request().url(),parsed=new URL(url);if(parsed.hostname==='127.0.0.1'&&parsed.port==='5000')return route.abort();if(parsed.hostname==='127.0.0.1')return route.continue();let f;
  if(url.includes('jszip@'))f=path.join(readers,'jszip/dist/jszip.min.js');
  else if(url.includes('pako@'))f=path.join(readers,'pako/dist/pako.min.js');
  else if(url.includes('utif@'))f=path.join(readers,'utif/UTIF.js');
  else if(url.includes('pdfjs-dist'))f=path.join(readers,'pdfjs-dist/build',path.basename(parsed.pathname));
  else if(url.includes('mammoth')&&url.includes('browser'))f=path.join(readers,'mammoth/mammoth.browser.min.js');
  else if(url.includes('tesseract.js-core'))f=path.join(readers,'tesseract.js-core',path.basename(parsed.pathname));
  else if(url.includes('tesseract.js@')&&url.includes('/dist/'))f=path.join(readers,'tesseract.js/dist',path.basename(parsed.pathname));
  else if(url.includes('eng.traineddata'))f=path.join(readers,'@tesseract.js-data/eng/4.0.0/eng.traineddata.gz');
  if(f&&fs.existsSync(f))return route.fulfill({status:200,body:fs.readFileSync(f),headers:{'Content-Type':f.endsWith('.wasm')?'application/wasm':f.endsWith('.gz')?'application/octet-stream':'text/javascript','Access-Control-Allow-Origin':'*'}});
  return route.fulfill({status:200,body:''});
 });
 await c.route('**/shared/supabase.js*',route=>route.fulfill({status:200,contentType:'text/javascript',body:`${baseMock}\nmock();(${fixture.toString()})();window.__wrapped=${wrapped};const cached=localStorage.getItem('__test_db');if(cached)window.__db=JSON.parse(cached);else{if(window.__wrapped)for(const name of Object.keys(window.__db))window.__db[name]=window.__db[name].map(row=>({id:row.id,data:row}));localStorage.setItem('__test_db',JSON.stringify(window.__db));}` }));
 await c.route('**/logo/enro.png',route=>route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><text x="4" y="25" fill="#047857">PG</text></svg>'}));
 return c;
}
async function page(c,name='officememo-admin'){const p=await c.newPage();p.on('pageerror',e=>errors.push({page:p.url(),message:e.message}));await p.goto(`http://127.0.0.1:8082/${name}.html`);await p.waitForFunction(()=>window.__db&&window.PGENRO_Module);await p.waitForTimeout(80);return p;}
async function test(name,fn){await fn();findings.push({scenario:name,result:'PASS'});console.log('PASS',name);}
async function open(p){await p.locator('#openCreateModalBtn').click();await p.locator('#memoFormModal.open').waitFor();await p.waitForTimeout(300);}
async function ocr(p,filename){await p.locator('#formPdfFile').setInputFiles(path.join(__dirname,filename));await p.locator('#runMemoOcrBtn').waitFor({state:'visible'});await p.waitForFunction(()=>!document.getElementById('runMemoOcrBtn').disabled);await p.locator('#runMemoOcrBtn').click();await p.waitForFunction(()=>!document.getElementById('saveMemoSubmitBtn').disabled,{},{timeout:120000});if(await p.locator('#formControlNo').inputValue()!=='2026-077')console.log('OCR DEBUG',await p.evaluate(()=>({raw:document.getElementById('memoOcrText').value,review:document.getElementById('memoExtractionReview').textContent,formBusy:document.getElementById('memoFormModal').dataset.busy,inert:document.getElementById('memoForm').inert,button:document.getElementById('runMemoOcrBtn').textContent,toasts:[...document.querySelectorAll('.toast')].map(e=>e.textContent),fields:[...document.querySelectorAll('#memoForm input,#memoForm textarea')].map(e=>({id:e.id,value:e.type==='hidden'?'':e.value,disabled:e.disabled}))})));assert.equal(await p.locator('#formControlNo').inputValue(),'2026-077');assert.equal(await p.locator('#formDate').inputValue(),'2026-10-01');assert.equal(await p.locator('#formAddressedTo').inputValue(),'ALL DIVISION HEADS');assert.equal(await p.locator('#formSubject').inputValue(),'SUBMISSION OF MONTHLY REPORTS');assert.equal(await p.locator('#formIssuedBy').inputValue(),'PROVINCIAL ENRO');}
(async()=>{
 await new Promise(r=>server.listen(8082,'127.0.0.1',r));const options={headless:true};if(process.env.PGENRO_CHROMIUM_EXECUTABLE){options.executablePath=process.env.PGENRO_CHROMIUM_EXECUTABLE;options.args=['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote'];}browser=await chromium.launch(options);
 async function newComm(c){const p=await page(c,'admincommunication');await p.locator('#openEncodingModalBtn').click();await p.waitForTimeout(300);return p;}
 async function read(p,input){await p.locator('#documentFileInput').setInputFiles(typeof input==='string'?path.join(__dirname,input):input);await p.locator('#runOcrBtn').click();await p.waitForFunction(()=>!document.getElementById('saveRecordBtn').disabled,{},{timeout:180000});}
 const expected={docTypeSelect:'Request Letter',controlNoInput:'REF-2026-181',dateInput:'2026-10-01',officeInput:'OFFICE OF THE MUNICIPAL MAYOR',subjectInput:'REQUEST FOR TECHNICAL ASSISTANCE FOR RIVER REHABILITATION'};
 async function assertIncoming(p){for(const[id,value]of Object.entries(expected))assert.equal(await p.locator('#'+id).inputValue(),value,id);assert.equal(await p.locator('#memoRecipientGroup').isVisible(),false);assert.equal(await p.locator('#dateFieldLabel').textContent(),'Date Received');assert((await p.locator('#communicationOcrReview').textContent()).includes('Printed issue date: 2026-09-20'));assert.equal(await p.locator('#actionTakenInput').inputValue(),'');}
 for(const name of (process.env.PROBE_FILE?[process.env.PROBE_FILE]:['incoming.txt','incoming.pdf','incoming.docx','incoming.png','scanned-incoming.pdf','mixed-incoming.pdf','unordered-incoming.pdf','incoming-sideways.png','incoming.jpg','incoming.webp','incoming.bmp','incoming.gif','incoming.tiff','incoming-deflate.tiff','incoming-multipage.tiff','incoming-scan.docx','incoming-banner-scan.docx']))await test(`Incoming mapping from real ${name}`,async()=>{const c=await context(),p=await newComm(c);await read(p,name);if((await p.locator('#officeInput').inputValue())!==expected.officeInput)console.log('EXTRACTION',name,await p.locator('#ocrTextInput').inputValue());await assertIncoming(p);await c.close();});
 await test('Actual included two-page scanned Office Order stays in Communications',async()=>{const c=await context(),p=await newComm(c);await read(p,{name:'actual-office-order.pdf',mimeType:'application/pdf',buffer:fs.readFileSync(path.join(root,'../User/uploads/tmp36gkc7tg.pdf'))});const values=await p.evaluate(()=>Object.fromEntries(['docTypeSelect','controlNoInput','dateInput','officeInput','subjectInput','ocrTextInput'].map(id=>[id,document.getElementById(id).value])));fs.writeFileSync(path.join(__dirname,'actual-office-order-extraction.json'),JSON.stringify(values,null,2));assert.equal(values.docTypeSelect,'Office Order');assert.equal(values.controlNoInput,'25-002, s. 2025');assert(values.subjectInput.includes('WORK AUGMENTATION AND SUPPORT DURING OFFICIAL TRAVEL'));assert(values.subjectInput.endsWith('SCHEDULED LEAVE OF ABSENCE'));assert.equal(values.officeInput,'EnP JOHN FRANCIS L. LUZANO, MPA');assert.notEqual(values.dateInput,'2025-01-02');assert(values.ocrTextInput.includes('\f'));assert.equal(await p.locator('#memoRecipientGroup').isVisible(),false);await p.locator('#encodingModal .modal-body').evaluate(el=>el.scrollTop=el.scrollHeight);await p.screenshot({path:path.join(__dirname,'incoming-review-desktop.png'),animations:'disabled'});await c.close();});
 await test('Printed author fills Received From and retains TO as recipient evidence',async()=>{const c=await context(),p=await newComm(c);await read(p,'signed-incoming.txt');assert.equal(await p.locator('#officeInput').inputValue(),'MARIA L. SANTOS');assert((await p.locator('#communicationReviewFields').textContent()).includes('PROVINCIAL ENRO'));assert((await p.locator('#communicationOcrReview').textContent()).includes('Printed sender'));await p.locator('#typeSelect').selectOption('Outgoing');assert.equal(await p.locator('#officeInput').inputValue(),'PROVINCIAL ENRO');await c.close();});
 await test('Mixed native PDF reads an image-only printed name and preserves native fields',async()=>{const c=await context(),p=await newComm(c);await read(p,'mixed-signatory.pdf');assert.equal(await p.locator('#officeInput').inputValue(),'MARIA L. SANTOS');assert.equal(await p.locator('#controlNoInput').inputValue(),'SIGNED-2026-201');assert.equal(await p.locator('#subjectInput').inputValue(),'REQUEST FOR TECHNICAL ASSISTANCE');assert.equal(await p.locator('#dateInput').inputValue(),'2026-10-01');assert(/Respectfully yours,[\s\S]*MARIA L\. SANTOS/.test(await p.locator('#ocrTextInput').inputValue()));await c.close();});
 await test('Legacy Incoming TO contamination is repaired without overwriting manual edits',async()=>{const c=await context(),p=await page(c,'admincommunication');await p.evaluate(()=>{window.__db.communications.push({id:'legacy-sender',type:'Incoming',docType:'Request Letter',controlNo:'LEGACY-01',date:'2026-10-01',office:'PROVINCIAL ENRO',subject:'Legacy sender',status:'Received',ocrText:''});localStorage.setItem('__test_db',JSON.stringify(window.__db));});await p.reload();await p.locator('[data-action="edit"][data-id="legacy-sender"]').click();await p.waitForTimeout(200);await read(p,'signed-incoming.txt');assert.equal(await p.locator('#officeInput').inputValue(),'MARIA L. SANTOS');assert((await p.locator('#communicationOcrReview').textContent()).includes('Printed sender'));await p.locator('#officeInput').fill('Reviewed manually');await p.locator('.encoder-text-details').evaluate(el=>el.open=true);await p.locator('#recheckCommunicationFieldsBtn').click();assert.equal(await p.locator('#officeInput').inputValue(),'Reviewed manually');await c.close();});
 await test('Outgoing uses TO and date released; received date is not reused',async()=>{const c=await context(),p=await newComm(c);await p.locator('#typeSelect').selectOption('Outgoing');await read(p,'incoming.txt');assert.equal(await p.locator('#officeInput').inputValue(),'PROVINCIAL ENRO');assert.equal(await p.locator('#dateFieldLabel').textContent(),'Date Released');assert((await p.locator('#communicationOcrReview').textContent()).includes('Confirm')||(await p.locator('#dateFieldHelp').textContent()).includes('actual'));await c.close();});
 await test('Changing direction remaps only untouched office and registry date',async()=>{const c=await context(),p=await newComm(c);await read(p,'incoming.txt');await p.locator('#typeSelect').selectOption('Outgoing');assert.equal(await p.locator('#officeInput').inputValue(),'PROVINCIAL ENRO');await p.locator('#officeInput').fill('Reviewed recipient');await p.locator('#typeSelect').selectOption('Incoming');assert.equal(await p.locator('#officeInput').inputValue(),'Reviewed recipient');await c.close();});
 await test('All manual corrections and deliberately empty fields survive a rerun',async()=>{const c=await context(),p=await newComm(c);await read(p,'incoming.txt');for(const[id,value]of Object.entries({controlNoInput:'MANUAL-011',dateInput:'2026-09-30',officeInput:'Verified office',subjectInput:'Verified subject',actionTakenInput:'Forwarded to reviewer',remarksInput:'Checked against original'}))await p.locator('#'+id).fill(value);await p.locator('#docTypeSelect').selectOption('Other Communication');await p.locator('#runOcrBtn').click();await p.waitForFunction(()=>!document.getElementById('saveRecordBtn').disabled);assert.equal(await p.locator('#controlNoInput').inputValue(),'MANUAL-011');assert.equal(await p.locator('#dateInput').inputValue(),'2026-09-30');assert.equal(await p.locator('#docTypeSelect').inputValue(),'Other Communication');assert.equal(await p.locator('#officeInput').inputValue(),'Verified office');assert.equal(await p.locator('#subjectInput').inputValue(),'Verified subject');await p.locator('#subjectInput').fill('');await p.locator('.encoder-text-details').evaluate(el=>el.open=true);await p.locator('#recheckCommunicationFieldsBtn').click();assert.equal(await p.locator('#subjectInput').inputValue(),'');await c.close();});
 await test('Rechecking corrected OCR clears stale fields and does not invent a sender',async()=>{const c=await context(),p=await newComm(c);await read(p,'incoming.txt');await p.locator('.encoder-text-details').evaluate(el=>el.open=true);await p.locator('#ocrTextInput').fill('REQUEST LETTER\nTO: Recipient only\nSUBJECT: Corrected reading\n\nDear Sir,\nFROM: Body reference');await p.locator('.encoder-text-details').evaluate(el=>el.open=true);await p.locator('#recheckCommunicationFieldsBtn').click();assert.equal(await p.locator('#officeInput').inputValue(),'');assert.equal(await p.locator('#subjectInput').inputValue(),'Corrected reading');assert((await p.locator('#controlNoInput').inputValue()).startsWith('COMM-'));assert((await p.locator('#communicationReviewFields').textContent()).includes('Review required'));await c.close();});
 await test('Removing an attachment clears automatic values while retaining manual ones',async()=>{const c=await context(),p=await newComm(c);await read(p,'incoming.txt');await p.locator('#subjectInput').fill('Keep my review');await p.locator('#removeDocumentBtn').click();assert.equal(await p.locator('#officeInput').inputValue(),'');assert.equal(await p.locator('#docTypeSelect').inputValue(),'');assert.equal(await p.locator('#subjectInput').inputValue(),'Keep my review');assert.equal(await p.locator('#ocrTextInput').inputValue(),'');assert.equal(await p.locator('#runOcrBtn').isDisabled(),true);await c.close();});
 for(const wrapped of [false,true])await test(`Incoming save retains fields, raw text and original attachment (${wrapped?'JSON data':'flat'})`,async()=>{const c=await context(wrapped),p=await newComm(c);await read(p,'incoming.txt');await p.locator('#saveRecordBtn').click();await p.locator('#encodingModal.open').waitFor({state:'hidden'});const saved=await p.evaluate(()=>window.__db.communications.map(r=>r.data||r));assert.equal(saved.length,1);assert.equal(saved[0].office,expected.officeInput);assert.equal(saved[0].subject,expected.subjectInput);assert(saved[0].ocrText.includes('September 20'));assert.equal(saved[0].fileName,'incoming.txt');assert(saved[0].attachmentId);assert.equal(await p.evaluate(()=>window.__db.office_memos.length),24);await c.close();});
 await test('Unreadable/corrupt files recover all controls and keep the draft',async()=>{const c=await context(),p=await newComm(c);await p.locator('#subjectInput').fill('My draft');await read(p,{name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('invalid PDF')});assert.equal(await p.locator('#subjectInput').inputValue(),'My draft');assert.equal(await p.locator('#browseDocumentBtn').isDisabled(),false);assert.equal(await p.locator('#ocrTextInput').isDisabled(),false);assert((await p.locator('#toastContainer').textContent()).length>0);await c.close();});
 await test('Memo review preserves deliberately cleared fields and clears old values for a letter',async()=>{const c=await context(),p=await page(c);await open(p);await ocr(p,'memo-fixture.txt');await p.locator('#formSubject').fill('');await p.locator('#recheckMemoFieldsBtn').click();assert.equal(await p.locator('#formSubject').inputValue(),'');await p.locator('#memoOcrText').fill('REQUEST LETTER\nTO: Mayor\nDATE: October 2, 2026\nSUBJECT: Ordinary letter');await p.locator('#recheckMemoFieldsBtn').click();assert.equal(await p.locator('#formAddressedTo').inputValue(),'');assert.equal(await p.locator('#formIssuedBy').inputValue(),'');assert.equal(await p.locator('#formDate').inputValue(),'');assert((await p.locator('#memoReviewSummary').textContent()).includes('heading'));await c.close();});
 await test('Communications extraction cards fit mobile and tablet forms',async()=>{const c=await context(),p=await newComm(c);await read(p,'incoming.txt');for(const width of [320,390,768]){await p.setViewportSize({width,height:800});await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#communicationExtractionReview').scrollIntoViewIfNeeded();const r=await p.locator('#communicationExtractionReview').boundingBox();assert(r.x>=0&&r.x+r.width<=width);if(width===390)await p.screenshot({path:path.join(__dirname,'incoming-review-mobile.png'),animations:'disabled'});}await c.close();});
 assert.deepEqual(errors,[],'No uncaught browser errors');
 fs.writeFileSync(path.join(__dirname,'incoming-browser-results.json'),JSON.stringify({method:'Actual production browser readers and module controllers; local pinned assets, simulated flat/JSON Supabase and real IndexedDB',scenarios:findings,uncaughtErrors:errors},null,2));console.log(findings.length+' incoming/OCR browser scenarios passed');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
