const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const root=path.join(process.env.PGENRO_PROJECT_ROOT?path.resolve(process.env.PGENRO_PROJECT_ROOT):path.resolve(__dirname,'../..'),'admin');
const baseMock=fs.readFileSync(path.join(__dirname,'mock.js'),'utf8').replace("Promise.resolve().then(()=>{","Promise.resolve().then(async()=>{if(window.__latency)await new Promise(r=>setTimeout(r,window.__latency));").replace("return {data:result.slice(q.lo,q.hi+1)","localStorage.setItem('__test_db',JSON.stringify(window.__db));return {data:result.slice(q.lo,q.hi+1)");
const readers=process.env.PGENRO_READERS_ROOT||path.join(__dirname,'node_modules');
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname;const f=path.join(root,name);if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404);return res.end('Not found');}res.setHeader('Content-Type',({'.css':'text/css','.html':'text/html','.js':'text/javascript'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});
const findings=[],errors=[];let browser;
function fixture(){const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;window.__db.office_memos=Array.from({length:24},(_,i)=>{const month=new Date(now.getFullYear(),now.getMonth()-i%6,1);return {id:'memo'+i,memoNo:`MEMO-2026-${String(i+1).padStart(3,'0')}`,date:`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-01`,addressedTo:'All Division Heads',subject:i%2?'Field inspection and reporting':'Submission of monthly work plans',issuedBy:'Provincial ENRO',remarks:'For review',isPinned:i<2,pdfUrl:i%2?'data:text/plain;base64,TWVtbw==':'',pdfFileName:i%2?'memo-fixture.txt':''};});window.__db.communications=[];window.__db.profiles=[];}
async function context(wrapped=false){
 const c=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Manila',acceptDownloads:true});
 await c.route('**/*',async route=>{
  const url=route.request().url(),parsed=new URL(url);if(parsed.hostname==='127.0.0.1')return route.continue();let f;
  if(url.includes('pako@'))f=path.join(readers,'pako/dist/pako.min.js');
  else if(url.includes('utif@'))f=path.join(readers,'utif/UTIF.js');
  else if(url.includes('pdfjs-dist'))f=path.join(readers,'pdfjs-dist/build',path.basename(parsed.pathname));
  else if(url.includes('mammoth')&&url.includes('browser'))f=path.join(readers,'mammoth/mammoth.browser.min.js');
  else if(url.includes('tesseract.js-core'))f=path.join(readers,'tesseract.js-core',path.basename(parsed.pathname));
  else if(url.includes('tesseract.js@')&&url.includes('/dist/'))f=path.join(readers,'tesseract.js/dist',path.basename(parsed.pathname));
  else if(url.includes('eng.traineddata'))f=path.join(readers,'@tesseract.js-data/eng/4.0.0/eng.traineddata.gz');
  if(f&&fs.existsSync(f))return route.fulfill({status:200,body:fs.readFileSync(f),headers:{'Content-Type':f.endsWith('.wasm')?'application/wasm':f.endsWith('.gz')?'application/octet-stream':'text/javascript','Access-Control-Allow-Origin':'*'}});
  return route.fulfill({status:200,body:''});
 });
 await c.route('**/shared/supabase.js*',route=>route.fulfill({status:200,contentType:'text/javascript',body:`${baseMock}\nmock();(${fixture.toString()})();window.__wrapped=${wrapped};const cached=localStorage.getItem('__test_db');if(cached)window.__db=JSON.parse(cached);else{if(window.__wrapped)for(const name of Object.keys(window.__db))window.__db[name]=window.__db[name].map(row=>({id:row.id,data:row}));localStorage.setItem('__test_db',JSON.stringify(window.__db));}` }));
 await c.route('**/logo/enro.png',route=>route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><text x="4" y="25" fill="#047857">PG</text></svg>'}));
 return c;
}
async function page(c,name='officememo-admin'){const p=await c.newPage();p.on('pageerror',e=>errors.push({page:p.url(),message:e.message}));await p.goto(`http://127.0.0.1:8065/${name}.html`);await p.waitForFunction(()=>window.__db&&window.PGENRO_Module);await p.waitForTimeout(80);return p;}
async function test(name,fn){await fn();findings.push({scenario:name,result:'PASS'});console.log('PASS',name);}
async function open(p){await p.locator('#openCreateModalBtn').click();await p.locator('#memoFormModal.open').waitFor();await p.waitForTimeout(300);}
async function ocr(p,filename){await p.locator('#formPdfFile').setInputFiles(path.join(__dirname,filename));await p.locator('#runMemoOcrBtn').waitFor({state:'visible'});await p.waitForFunction(()=>!document.getElementById('runMemoOcrBtn').disabled);await p.locator('#runMemoOcrBtn').click();await p.waitForFunction(()=>!document.getElementById('saveMemoSubmitBtn').disabled,{},{timeout:120000});if(await p.locator('#formControlNo').inputValue()!=='2026-077')console.log('OCR DEBUG',await p.evaluate(()=>({raw:document.getElementById('memoOcrText').value,review:document.getElementById('memoExtractionReview').textContent,formBusy:document.getElementById('memoFormModal').dataset.busy,inert:document.getElementById('memoForm').inert,button:document.getElementById('runMemoOcrBtn').textContent,toasts:[...document.querySelectorAll('.toast')].map(e=>e.textContent),fields:[...document.querySelectorAll('#memoForm input,#memoForm textarea')].map(e=>({id:e.id,value:e.type==='hidden'?'':e.value,disabled:e.disabled}))})));assert.equal(await p.locator('#formControlNo').inputValue(),'2026-077');assert.equal(await p.locator('#formDate').inputValue(),'2026-10-01');assert.equal(await p.locator('#formAddressedTo').inputValue(),'ALL DIVISION HEADS');assert.equal(await p.locator('#formSubject').inputValue(),'SUBMISSION OF MONTHLY REPORTS');assert.equal(await p.locator('#formIssuedBy').inputValue(),'PROVINCIAL ENRO');}
(async()=>{
 await new Promise(r=>server.listen(8065,'127.0.0.1',r));const options={headless:true};if(process.env.PGENRO_CHROMIUM_EXECUTABLE){options.executablePath=process.env.PGENRO_CHROMIUM_EXECUTABLE;options.args=['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote'];}browser=await chromium.launch(options);
 const c=await context(),p=await page(c);
 if(process.env.PROBE_UI){for(const width of [320,390,768]){await p.setViewportSize({width,height:800});await open(p);await p.waitForTimeout(300);console.log(width,await p.locator('.memo-form-modal').evaluate(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height,style:getComputedStyle(el).maxHeight,body:getComputedStyle(el.querySelector('.memo-form-body')).overflowY};}));await p.screenshot({path:path.join(__dirname,'form-probe-'+width+'.png')});await p.keyboard.press('Escape');}return;}
 await test('Dashboard aggregates, accessible six-month chart and consistent admin navigation',async()=>{assert.equal(await p.locator('#kpiTotalMemos').textContent(),'24');assert.equal(await p.locator('#kpiPinnedMemos').textContent(),'2');assert.equal(await p.locator('#kpiWithAttachments').textContent(),'12');assert.equal(await p.locator('.memo-month-column').count(),6);assert.equal(await p.locator('.memo-quick-item').count(),3);const g=await p.evaluate(()=>({sidebar:document.querySelector('#sidebar').getBoundingClientRect().width,topbar:document.querySelector('.topbar').getBoundingClientRect().height,nav:document.querySelector('.nav-item').getBoundingClientRect().height,overflow:document.documentElement.scrollWidth>innerWidth}));assert.deepEqual(g,{sidebar:275,topbar:70,nav:36,overflow:false});await p.screenshot({path:path.join(__dirname,'memo-dashboard-desktop.png'),fullPage:true,animations:'disabled'});});
 await test('Pagination survives refresh and selection drives selected CSV export',async()=>{await p.getByRole('button',{name:'Page 2',exact:true}).click();await p.locator('#refreshMemosBtn').click();assert((await p.locator('#memoPaginationInfo').textContent()).includes('Showing 9 to 16'));await p.locator('.row-checkbox').first().check();assert((await p.locator('#exportCsvBtn').textContent()).includes('Export Selected (1)'));const [download]=await Promise.all([p.waitForEvent('download'),p.locator('#exportCsvBtn').click()]);const f=await download.path();assert.equal(fs.readFileSync(f,'utf8').split('\r\n').length,2);await p.locator('#clearMemoSelectionBtn').click();await p.locator('#clearMemoFiltersBtn').click();});
 for(const filename of ['memo-fixture.txt','memo.pdf','memo.docx','memo.png','scanned-memo.pdf','memo-deflate.tiff','memo.gif','memo-scan.docx'])await test(`Real ${filename} extraction produces the same five fields`,async()=>{await open(p);await ocr(p,filename);await p.locator('#cancelFormModalBtn').click();});
 await test('Manual number, date, recipient and issuer survive OCR',async()=>{await open(p);const number=await p.locator('#formControlNo').inputValue();await p.locator('#formControlNo').fill(number);await p.locator('#formDate').fill('2026-09-29');await p.locator('#formAddressedTo').fill('Reviewed recipients');await p.locator('#formIssuedBy').fill('Reviewed signatory');await p.locator('#formPdfFile').setInputFiles(path.join(__dirname,'memo-fixture.txt'));await p.waitForFunction(()=>!document.getElementById('runMemoOcrBtn').disabled);await p.locator('#runMemoOcrBtn').click();await p.waitForFunction(()=>!document.getElementById('saveMemoSubmitBtn').disabled);assert.equal(await p.locator('#formControlNo').inputValue(),number);assert.equal(await p.locator('#formDate').inputValue(),'2026-09-29');assert.equal(await p.locator('#formAddressedTo').inputValue(),'Reviewed recipients');assert.equal(await p.locator('#formIssuedBy').inputValue(),'Reviewed signatory');await p.locator('#cancelFormModalBtn').click();});
 await test('OCR preserves manual edits and incomplete/ambiguous fields need review',async()=>{await open(p);await p.locator('#formSubject').fill('Manually reviewed subject');await p.locator('#formSubject').dispatchEvent('input');await p.locator('#formPdfFile').setInputFiles(path.join(__dirname,'memo-fixture.txt'));await p.waitForFunction(()=>!document.getElementById('runMemoOcrBtn').disabled);await p.locator('#runMemoOcrBtn').click();await p.waitForFunction(()=>!document.getElementById('saveMemoSubmitBtn').disabled);assert.equal(await p.locator('#formSubject').inputValue(),'Manually reviewed subject');assert((await p.locator('#memoReviewFields').textContent()).includes('Manual value kept'));await p.locator('#memoOcrText').fill('MEMORANDUM NO. 2026-077\nTO: All Personnel\nDATE: 09/10/2026\nSUBJECT: Reports');await p.locator('#recheckMemoFieldsBtn').click();assert.equal(await p.locator('#formDate').inputValue(),'');assert((await p.locator('#memoReviewSummary').textContent()).includes('ambiguous'));await p.locator('#cancelFormModalBtn').click();});
 await test('Attachment replacement clears old auto-fill without erasing manual subject',async()=>{await open(p);await ocr(p,'memo-fixture.txt');await p.locator('#formSubject').fill('Kept manually');await p.locator('#formPdfFile').setInputFiles({name:'other.txt',mimeType:'text/plain',buffer:Buffer.from('MEMORANDUM NO. 2026-078\nTO: Chiefs\nDATE: October 2, 2026\nSUBJECT: New directive')});await p.waitForFunction(()=>!document.getElementById('saveMemoSubmitBtn').disabled);assert.equal(await p.locator('#memoOcrText').inputValue(),'');assert.equal(await p.locator('#formSubject').inputValue(),'Kept manually');assert.equal(await p.locator('#formAddressedTo').inputValue(),'');await p.locator('#cancelFormModalBtn').click();});
 await test('Whitespace-only required values and duplicate numbers cannot save',async()=>{await open(p);await p.locator('#formSubject').fill('   ');await p.locator('#formAddressedTo').fill('Heads');await p.locator('#saveMemoSubmitBtn').click();assert.equal(await p.evaluate(()=>window.__db.office_memos.length),24);await p.locator('#formSubject').fill('Reports');await p.locator('#formControlNo').fill('MEMO-2026-001');await p.locator('#saveMemoSubmitBtn').click();assert.equal(await p.evaluate(()=>window.__db.office_memos.length),24);await p.locator('#cancelFormModalBtn').click();});
 await test('Denied save preserves form and controls recover; preview returns to draft',async()=>{await open(p);await ocr(p,'memo-fixture.txt');await p.locator('#previewSelectedPdfBtn').click();await p.locator('#viewPdfModal.open').waitFor();await p.keyboard.press('Escape');await p.locator('#memoFormModal.open').waitFor();assert.equal(await p.locator('#formSubject').inputValue(),'SUBMISSION OF MONTHLY REPORTS');await p.evaluate(()=>window.__deny=true);await p.locator('#saveMemoSubmitBtn').click();await p.waitForFunction(()=>!document.getElementById('saveMemoSubmitBtn').disabled);assert.equal(await p.locator('#formSubject').inputValue(),'SUBMISSION OF MONTHLY REPORTS');assert.equal(await p.locator('#memoFormModal.open').count(),1);await p.evaluate(()=>window.__deny=false);await p.locator('#saveMemoSubmitBtn').click();await p.locator('#memoFormModal.open').waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>window.__db.office_memos.length),25);});
 await test('Saved raw text stays available after editing while remarks remain usable',async()=>{await p.locator('#tableFilterInput').fill('2026-077');await p.locator('.edit-memo-btn').click();assert((await p.locator('#memoOcrText').inputValue()).includes('OFFICE MEMORANDUM'));assert.equal(await p.locator('#formRemarks').inputValue(),'');await p.locator('#formRemarks').fill('Approved for release');await p.locator('#saveMemoSubmitBtn').click();await p.locator('#memoFormModal.open').waitFor({state:'hidden'});assert((await p.locator('.memo-remarks-preview').textContent()).includes('Approved for release'));});
 await test('320px, 390px and tablet layouts have usable centered scrollable forms',async()=>{for(const width of [320,390,768]){await p.setViewportSize({width,height:800});await p.locator('#clearMemoFiltersBtn').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await open(p);const g=await p.locator('.memo-form-modal').evaluate(el=>{const r=el.getBoundingClientRect(),b=el.querySelector('.memo-form-body');return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,overflow:getComputedStyle(b).overflowY};});assert(g.left>=0&&g.right<=width&&g.top>=0&&g.bottom<=800);assert(['auto','scroll'].includes(g.overflow));await p.locator('.memo-form-body').evaluate(el=>el.scrollTop=el.scrollHeight);await p.locator('#saveMemoSubmitBtn').waitFor({state:'visible'});if(width===390)await p.screenshot({path:path.join(__dirname,'memo-form-mobile.png'),animations:'disabled'});await p.keyboard.press('Escape');}await p.setViewportSize({width:1440,height:1000});});
 await test('Busy form cannot be reset by create action',async()=>{await open(p);await p.locator('#formAddressedTo').fill('Heads');await p.locator('#formSubject').fill('Slow save');await p.evaluate(()=>window.__latency=120);await p.locator('#saveMemoSubmitBtn').click();await p.evaluate(()=>document.getElementById('openCreateModalBtn').click());assert.equal(await p.locator('#formSubject').inputValue(),'Slow save');await p.locator('#memoFormModal.open').waitFor({state:'hidden'});await p.evaluate(()=>window.__latency=0);});
 await p.screenshot({path:path.join(__dirname,'memo-dashboard-final.png'),fullPage:true,animations:'disabled'});await c.close();
 for(const wrapped of [false,true])await test(`Communications OCR saves and redirects with original attachment (${wrapped?'JSON envelope':'flat'})`,async()=>{const cc=await context(wrapped),q=await page(cc,'admincommunication');await q.locator('#openEncodingModalBtn').click();await q.locator('#documentFileInput').setInputFiles(path.join(__dirname,'memo-fixture.txt'));await q.locator('#runOcrBtn').click();await q.waitForFunction(()=>!document.getElementById('saveRecordBtn').disabled);assert.equal(await q.locator('#docTypeSelect').inputValue(),'Memorandum');assert.equal(await q.locator('#subjectInput').inputValue(),'SUBMISSION OF MONTHLY REPORTS');await Promise.all([q.waitForURL('**/officememo-admin.html?**'),q.locator('#saveRecordBtn').click()]);await q.waitForFunction(()=>document.getElementById('tableFilterInput').value==='2026-077');const rows=await q.evaluate(()=>window.__db.office_memos.map(m=>m.data||m));assert.equal(rows.length,25);assert(rows.some(m=>m.memoNo==='2026-077'&&m.pdfFileName==='memo-fixture.txt'&&m.pdfUrl.startsWith('data:text/plain;')));assert.equal(await q.evaluate(()=>window.__db.communications.length),0);assert((await q.locator('#memoAdminTableBody').textContent()).includes('2026-077'));await cc.close();});
 assert.deepEqual(errors,[],'No uncaught browser errors');
 fs.writeFileSync(path.join(__dirname,'memo-browser-results.json'),JSON.stringify({method:'Chromium with simulated Supabase; real PDF.js, Mammoth and Tesseract reader assets served locally at their pinned versions',scenarios:findings,uncaughtErrors:errors},null,2));console.log(findings.length+' browser scenarios passed');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
