const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../admincommunication.js'),'utf8');
const report=[];
const formIds=['typeSelect','controlNoInput','docTypeSelect','dateInput','officeInput','subjectInput','actionTakenInput','remarksInput','statusSelect','ocrTextInput','memoRecipientInput','memoIssuerInput','documentFileInput','editIndex'];
const memoText=(number='2026-099')=>`Republic of the Philippines\nProvincial Government\nOFFICE MEMORANDUM NO. ${number}\n\nTO: All Personnel\nFROM: Provincial ENRO\nDATE: September 30, 2026\nSUBJECT: Monthly reporting\n\nPlease submit the reports.\n`;
function setup({wrapped=false,live=true,communications=[],memos=[]}={}){
 const nodes=new Map(),listeners=new Map(),db={communications:structuredClone(communications),office_memos:structuredClone(memos),audit_logs:[]},storage=new Map(),files=new Map(),messages=[],navigation=[];
 if(wrapped)for(const name of Object.keys(db))db[name]=db[name].map(r=>({id:r.id,data:r}));
 let context;
 class Element{
  constructor(id=''){this.id=id;this.value='';this.textContent='';this.style={};this.dataset={};this.disabled=false;this.required=false;this.hidden=false;this.files=[];this.listeners=new Map();this.attributes={};this.children=[];this.options=[];this.parentElement={setAttribute(){}};const classes=new Set();this.classList={add:(s)=>classes.add(s),remove:(s)=>classes.delete(s),contains:(s)=>classes.has(s),toggle:(s,on)=>{if(on??!classes.has(s))classes.add(s);else classes.delete(s);}};}
  addEventListener(type,fn){const list=this.listeners.get(type)||[];list.push(fn);this.listeners.set(type,list);}
  async fire(type,event={}){for(const fn of this.listeners.get(type)||[])await fn({preventDefault(){},target:this,...event});}
  dispatchEvent(event){return true;}
  querySelector(selector){if(!this.child)this.child=new Element();return this.child;}
  querySelectorAll(){return this.id==='communicationForm'?formIds.map(get):[];}
  setAttribute(key,value){this.attributes[key]=value;}
  removeAttribute(key){delete this.attributes[key];}
  replaceChildren(...items){this.children=items;}
  add(item){this.children.push(item);}
  append(item){this.children.push(item);item.parent=this;if(this.id==='toastContainer')messages.push(item.textContent);}
  get firstElementChild(){return this.children[0];}
  remove(){if(this.parent)this.parent.children=this.parent.children.filter(item=>item!==this);}
  closest(){return this;}
  focus(){}
  reset(){for(const id of formIds)get(id).value='';}
  reportValidity(){return formIds.every(id=>{const e=get(id);return e.disabled||!e.required||e.value.trim();});}
 }
 const get=id=>{if(!nodes.has(id))nodes.set(id,new Element(id));return nodes.get(id);};
 for(const id of ['typeSelect','controlNoInput','docTypeSelect','dateInput','officeInput','subjectInput','statusSelect'])get(id).required=true;
 const document={title:'PGENRO IMS | Communications Log Admin',readyState:'loading',activeElement:null,body:new Element('body'),head:new Element('head'),getElementById:get,createElement:()=>new Element(),createElementNS:()=>new Element(),querySelector:()=>null,querySelectorAll:()=>[],addEventListener(type,fn){const l=listeners.get(type)||[];l.push(fn);listeners.set(type,l);}};
 const flags={fail:false,denyInsert:false,denyDelete:false,unknownInsert:false,unknownDelete:false,delay:0};
 const calls=[];
 function from(table){const q={op:'read',cols:'*',ids:null,body:null,lo:0,hi:Infinity},query={select(cols){q.cols=cols;return query;},order(){return query;},range(lo,hi){q.lo=lo;q.hi=hi;return query;},limit(n){q.hi=n-1;return query;},eq(k,v){q.ids=[String(v)];return query;},in(k,v){q.ids=v.map(String);return query;},insert(body){q.op='insert';q.body=body;return query;},update(body){q.op='update';q.body=body;return query;},delete(){q.op='delete';return query;},then(resolve,reject){return (async()=>{
  if(flags.delay)await new Promise(r=>setTimeout(r,flags.delay));
  if(flags.fail)return {data:null,error:{message:'Simulated outage',code:'503'}};
  if(q.cols==='data'&&!wrapped)return {data:null,error:{message:'Column data not found',code:'42703'}};
  const rows=db[table]||=[];let result=q.ids?rows.filter(r=>q.ids.includes(String(r.id))):rows;
  if(q.op==='insert'){
   calls.push({table,op:q.op,body:structuredClone(q.body)});
   if(flags.denyInsert&&table==='office_memos')return {data:[],error:null};
   assert(!rows.some(r=>r.id===q.body.id),'duplicate database ID');
   result=[{...structuredClone(q.body),id:q.body.id||crypto.randomUUID()}];rows.push(...result);
   if(flags.unknownInsert&&table==='office_memos'){flags.unknownInsert=false;throw new Error('Connection interrupted after insert');}
  }
  if(q.op==='delete'){
   calls.push({table,op:q.op});if(flags.denyDelete&&table==='communications')return {data:[],error:null};
   db[table]=rows.filter(r=>!q.ids.includes(String(r.id)));
   if(flags.unknownDelete&&table==='communications'){flags.unknownDelete=false;throw new Error('Connection interrupted after delete');}
  }
  if(q.op==='update')result.forEach(r=>Object.assign(r,q.body));
  return {data:structuredClone(result.slice(q.lo,q.hi+1)),count:result.length,error:null};
 })().then(resolve,reject);}};return query;}
 const indexedDB={open(){const req={};setImmediate(()=>{req.result={transaction(){const tx={objectStore(){return {put(value,id){return operation('put',id,value);},get(id){return operation('get',id);},delete(id){return operation('delete',id);}};}};function operation(action,id,value){const r={};setImmediate(()=>{if(action==='put')files.set(id,value);if(action==='delete')files.delete(id);r.result=files.get(id);r.onsuccess?.();tx.oncomplete?.();});return r;}return tx;}};req.onsuccess?.();});return req;}};
 class Reader{readAsDataURL(blob){blob.arrayBuffer().then(buffer=>{this.result=`data:${blob.type};base64,${Buffer.from(buffer).toString('base64')}`;this.onload();},()=>this.onerror());}}
 const location={href:'http://localhost/admin/admincommunication.html',assign:url=>navigation.push(url)};
 const sandbox={document,window:null,location,history:{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},indexedDB,FileReader:Reader,File,Blob,URL,crypto,console,Event,AbortController,DOMException,TextDecoder,performance,Option:Element,setInterval,clearInterval,setTimeout:(fn,t)=>{if(t>1000)return 0;return setTimeout(fn,t);},clearTimeout,innerWidth:1440,confirm:()=>true};
 sandbox.window=sandbox;sandbox.addEventListener=()=>{};
 if(live)sandbox.pgenroSupabase={from,channel(){return {on(){return this;},subscribe(){return this;}}},removeChannel(){}};
 context=vm.createContext(sandbox);
 vm.runInContext(source,context);
 async function init(){for(const callback of listeners.get('DOMContentLoaded')||[])await callback();}
 async function open(id){if(id){const b=new Element();b.dataset={action:'edit',id};await get('communicationTableBody').fire('click',{target:{closest:()=>b}});if(get('docTypeSelect').value==='Memorandum'&&!get('memoRecipientInput').value)get('memoRecipientInput').value='All Personnel';}else await get('openEncodingModalBtn').fire('click');}
 async function upload(text=memoText(),name='memo.txt'){const file=new File([text],name,{type:'text/plain'});get('documentFileInput').files=[file];await get('documentFileInput').fire('change');await get('runOcrBtn').fire('click');return file;}
 const rows=table=>db[table].map(r=>wrapped?r.data:r);
 return {init,open,upload,get,flags,db,rows,storage,files,messages,navigation,calls,save:()=>get('communicationForm').fire('submit')};
}
async function run(name,fn){await fn();report.push({scenario:name,result:'PASS'});console.log('PASS',name);}
(async()=>{
 for(const wrapped of [false,true])await run(`Detected memo routes with full attachment and fields (${wrapped?'JSON envelope':'flat columns'})`,async()=>{
  const s=setup({wrapped});await s.init();await s.open();await s.upload();
  assert.equal(s.get('docTypeSelect').value,'Memorandum');assert.equal(s.get('controlNoInput').value,'2026-099');assert.equal(s.get('dateInput').value,'2026-09-30');assert.equal(s.get('memoRecipientInput').value,'All Personnel');assert.equal(s.get('memoIssuerInput').value,'Provincial ENRO');assert.equal(s.get('subjectInput').value,'Monthly reporting');assert.equal(s.get('memoRecipientGroup').hidden,false);
  s.get('subjectInput').value='Reviewed subject';await s.save();assert.equal(s.rows('communications').length,0);const m=s.rows('office_memos')[0];assert.equal(m.subject,'Reviewed subject');assert.equal(m.addressedTo,'All Personnel');assert.equal(m.issuedBy,'Provincial ENRO');assert.equal(m.pdfFileName,'memo.txt');assert.equal(Buffer.from(m.pdfUrl.split(',')[1],'base64').toString(),memoText());assert(m.remarks.includes('Extracted document text:'));assert(s.navigation[0].includes('officememo-admin.html?memo='));
  const allowed=['memoNo','date','addressedTo','issuedBy','subject','title','remarks','isPinned','pdfUrl','pdfFileName','createdAt','updatedAt','id'];assert(Object.keys(m).every(k=>allowed.includes(k)));
 });
 for(const wrapped of [false,true])await run(`Memo printed signature becomes issuer and routes to Office Memos (${wrapped?'JSON':'flat'})`,async()=>{const s=setup({wrapped});await s.init();await s.open();const text='OFFICE MEMORANDUM NO. SIGNED-2026-101\nTO: ALL PERSONNEL\nDATE: October 1, 2026\nSUBJECT: Reports\n\nPlease submit the reports.\n\nFor your compliance.\n\nMARIA L. SANTOS\nDepartment Head';await s.upload(text,'signed-memo.txt');assert.equal(s.get('memoRecipientInput').value,'ALL PERSONNEL');assert.equal(s.get('memoIssuerInput').value,'MARIA L. SANTOS');await s.save();assert.equal(s.rows('communications').length,0);assert.equal(s.rows('office_memos')[0].issuedBy,'MARIA L. SANTOS');assert.equal(s.rows('office_memos')[0].addressedTo,'ALL PERSONNEL');assert.equal(s.rows('office_memos')[0].pdfFileName,'signed-memo.txt');assert(s.navigation[0].includes('officememo-admin.html?memo='));});
 for(const wrapped of [false,true])await run(`First-line TO saved as Incoming sender is corrected (${wrapped?'JSON':'flat'})`,async()=>{const s=setup({wrapped,communications:[{id:'legacy-sender',type:'Incoming',docType:'Office Order',controlNo:'OLD-01',date:'2026-10-01',office:'ALL PERSONNEL',subject:'Work',status:'Received'}]});await s.init();await s.open('legacy-sender');await s.upload('OFFICE ORDER NO. 025\nTO: ALL PERSONNEL\nPG ENRO\nDATE: October 1, 2026\nSUBJECT: Work\n\nPlease comply.\n\nFor your compliance.\n\nMARIA L. SANTOS\nDepartment Head','order.txt');assert.equal(s.get('officeInput').value,'MARIA L. SANTOS');assert.equal(s.get('docTypeSelect').value,'Office Order');assert(s.get('communicationOcrReview').textContent.includes('TO recipient'));});
 await run('Body references and filename do not classify a letter as a memo',async()=>{const s=setup();await s.init();await s.open();await s.upload('REQUEST LETTER\nFROM: Mayor\nTO: ENRO\nSUBJECT: Follow up on Memorandum 12\n\nDear Sir,\nMEMORANDUM\nPlease provide the referenced copy.','memorandum-reference.txt');assert.equal(s.get('docTypeSelect').value,'Request Letter');assert.equal(s.get('memoRecipientGroup').hidden,true);s.get('docTypeSelect').value='Request Letter';await s.get('docTypeSelect').fire('input');await s.get('docTypeSelect').fire('change');await s.save();assert.equal(s.rows('communications').length,1);assert.equal(s.rows('office_memos').length,0);assert.equal(s.navigation.length,0);});
 await run('Duplicate memo number keeps attachment and form without inserting',async()=>{const s=setup({memos:[{id:'existing',memoNo:'2026-099'}]});await s.init();await s.open();await s.upload();await s.save();assert.equal(s.rows('office_memos').length,1);assert.equal(s.navigation.length,0);assert(s.messages.some(m=>m.includes('already exists')));assert.equal(s.get('docTypeSelect').disabled,false);});
 await run('Permission-denied insert keeps source communication and form',async()=>{const s=setup({communications:[{id:'source',controlNo:'2026-099',docType:'Memorandum',type:'Incoming',date:'2026-09-30',office:'All Personnel',subject:'Monthly reporting',status:'Pending'}]});await s.init();await s.open('source');s.flags.denyInsert=true;await s.save();assert.equal(s.rows('office_memos').length,0);assert.equal(s.rows('communications').length,1);assert.equal(s.navigation.length,0);assert(s.messages.some(m=>m.includes('not saved')));});
 for(const wrapped of [false,true])await run(`Unknown insert result retries without duplicate (${wrapped?'JSON':'flat'})`,async()=>{const s=setup({wrapped});await s.init();await s.open();await s.upload();s.flags.unknownInsert=true;await s.save();assert.equal(s.rows('office_memos').length,1);assert.equal(s.navigation.length,0);await s.save();assert.equal(s.rows('office_memos').length,1);assert.equal(s.calls.filter(c=>c.table==='office_memos'&&c.op==='insert').length,1);assert.equal(s.navigation.length,1);});
 await run('Delete denial retains source; retry finishes move using saved memo',async()=>{const s=setup({communications:[{id:'source',controlNo:'2026-099',docType:'Memorandum',type:'Incoming',date:'2026-09-30',office:'All Personnel',subject:'Monthly reporting',status:'Pending',attachmentId:'blob1',fileName:'original.pdf'}]});s.files.set('blob1',new File(['original-pdf-bytes'],'original.pdf',{type:'application/pdf'}));await s.init();await s.open('source');s.flags.denyDelete=true;await s.save();assert.equal(s.rows('office_memos').length,1);assert.equal(s.rows('communications').length,1);assert(s.files.has('blob1'));assert.equal(s.get('saveRecordBtn').querySelector('span').textContent,'Finish Move to Office Memos');assert.equal(s.get('docTypeSelect').disabled,true);s.flags.denyDelete=false;await s.save();assert.equal(s.rows('office_memos').length,1);assert.equal(s.rows('communications').length,0);assert.equal(s.navigation.length,1);assert.equal(Buffer.from(s.rows('office_memos')[0].pdfUrl.split(',')[1],'base64').toString(),'original-pdf-bytes');});
 await run('Unknown delete result can finish an already completed move',async()=>{const s=setup({communications:[{id:'source',controlNo:'2026-099',docType:'Memorandum',type:'Incoming',date:'2026-09-30',office:'Personnel',subject:'Reporting',status:'Pending'}]});await s.init();await s.open('source');s.flags.unknownDelete=true;await s.save();assert.equal(s.rows('communications').length,0);await s.save();assert.equal(s.rows('office_memos').length,1);assert.equal(s.navigation.length,1);});
 await run('Missing original attachment prevents move and source deletion',async()=>{const s=setup({communications:[{id:'source',controlNo:'2026-099',docType:'Memorandum',type:'Incoming',date:'2026-09-30',office:'Personnel',subject:'Reporting',status:'Pending',attachmentId:'missing',fileName:'memo.pdf'}]});await s.init();await s.open('source');await s.save();assert.equal(s.rows('office_memos').length,0);assert.equal(s.rows('communications').length,1);assert(s.messages.some(m=>m.includes('Reattach')));});
 await run('Oversized memo attachment is rejected without a database write',async()=>{const s=setup();await s.init();await s.open();const f=new File([memoText(),'x'.repeat(10*1024*1024)],'memo.txt',{type:'text/plain'});s.get('documentFileInput').files=[f];await s.get('documentFileInput').fire('change');s.get('ocrTextInput').value=memoText();await s.get('ocrTextInput').fire('change');await s.save();assert.equal(s.rows('office_memos').length,0);assert(s.messages.some(m=>m.includes('10 MB')));});
 await run('Double submit inserts only one memo',async()=>{const s=setup();await s.init();await s.open();await s.upload();s.flags.delay=5;await Promise.all([s.save(),s.save()]);assert.equal(s.rows('office_memos').length,1);});
 await run('Manual document-type correction routes to Communications',async()=>{const s=setup();await s.init();await s.open();await s.upload();s.get('docTypeSelect').value='Request Letter';await s.get('docTypeSelect').fire('input');await s.get('docTypeSelect').fire('change');await s.save();assert.equal(s.rows('communications').length,1);assert.equal(s.rows('office_memos').length,0);});
 await run('Replacing a detected file clears stale classification and OCR',async()=>{const s=setup();await s.init();await s.open();await s.upload();s.get('documentFileInput').files=[new File(['REQUEST LETTER'],'letter.txt',{type:'text/plain'})];await s.get('documentFileInput').fire('change');assert.equal(s.get('docTypeSelect').value,'');assert.equal(s.get('ocrTextInput').value,'');assert.equal(s.get('memoRecipientInput').value,'');});
 await run('Offline memo upload remains unsaved with an actionable error',async()=>{const s=setup({live:false});await s.init();await s.open();await s.upload();await s.save();assert.equal(s.rows('office_memos').length,0);assert.equal(s.navigation.length,0);assert(s.messages.some(m=>m.includes('Connect to the database')));});
 await run('Heading variants and impossible dates are handled safely',async()=>{for(const heading of ['MEMORANDUM','MEMORANDUM CIRCULAR NO. 2026-015','MEMORANDUM FOR: All Personnel','Office Memo No. 2026-015','MEMORANDUM NO. 015, S. 2026','MEMORANDUM 2026-015']){const s=setup();await s.init();await s.open();await s.upload(`${heading}\n\nTO: All Personnel\nDATE: February 30, 2026\nSUBJECT: Report\n\nPlease report.`);assert.equal(s.get('docTypeSelect').value,'Memorandum');assert.notEqual(s.get('dateInput').value,'2026-02-30');if(heading.includes('015'))assert(s.get('controlNoInput').value.includes('015'));}});
 await run('Replacing extracted text clears an obsolete automatic memo classification',async()=>{const s=setup();await s.init();await s.open();await s.upload();s.get('ocrTextInput').value='REQUEST LETTER\nSUBJECT: Copy of a memorandum\n\nDear Sir';await s.get('ocrTextInput').fire('change');assert.equal(s.get('docTypeSelect').value,'Request Letter');});
 await run('Reopening a pending move restores its saved destination and prevents another record',async()=>{const s=setup({communications:[{id:'source',controlNo:'2026-099',docType:'Memorandum',type:'Incoming',date:'2026-09-30',office:'Personnel',subject:'Reporting',status:'Pending'}]});await s.init();await s.open('source');s.flags.denyDelete=true;await s.save();await s.get('cancelEncodingBtn').fire('click');await s.open('source');assert.equal(s.get('docTypeSelect').disabled,true);assert.equal(s.get('saveRecordBtn').querySelector('span').textContent,'Finish Move to Office Memos');s.flags.denyDelete=false;await s.save();assert.equal(s.rows('office_memos').length,1);assert.equal(s.rows('communications').length,0);});
 await run('Manual memorandum selection validates recipient and saves without an attachment',async()=>{const s=setup();await s.init();await s.open();s.get('docTypeSelect').value='Memorandum';await s.get('docTypeSelect').fire('change');assert.equal(s.get('controlNoInput').value,'');s.get('controlNoInput').value='MANUAL-2026-001';s.get('subjectInput').value='Manual memo';await s.save();assert.equal(s.rows('office_memos').length,0);s.get('memoRecipientInput').value='All Personnel';await s.save();assert.equal(s.rows('office_memos')[0].pdfUrl,'');assert.equal(s.rows('office_memos')[0].memoNo,'MANUAL-2026-001');});
 await run('Unavailable retry storage blocks upload before a database mutation',async()=>{const s=setup();await s.init();await s.open();await s.upload();const set=s.storage.set.bind(s.storage);s.storage.set=(k,v)=>{if(k==='pgenro_memo_routes')throw new Error('Storage blocked');return set(k,v);};await s.save();assert.equal(s.rows('office_memos').length,0);assert(s.messages.some(m=>m.includes('Browser storage is unavailable')));});
 const memoSource=fs.readFileSync(path.join(__dirname,'../officememo-admin.js'),'utf8');
 await run('Office Memo preview accepts transferred MIME types and rejects HTML/JavaScript',async()=>{const start=memoSource.indexOf('  function safeAttachment('),end=memoSource.indexOf('  // Render pages ourselves',start);const fn=memoSource.slice(start,end);const safe=vm.runInNewContext(`(${fn.trim()})`,{URL,location:{href:'http://localhost/admin/officememo-admin.html'}});for(const type of ['application/pdf','image/png','image/jpeg','image/webp','image/bmp','image/tiff','text/plain','text/csv','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.presentationml.presentation'])assert(safe(`data:${type};base64,dGVzdA==`));for(const value of ['javascript:alert(1)','data:text/html;base64,dGVzdA==','data:image/svg+xml;base64,dGVzdA=='])assert.equal(safe(value),'');});
 fs.writeFileSync(path.join(__dirname,'memorandum_routing.json'),JSON.stringify({method:'Node VM event-driven DOM harness with actual module database runtime and simulated Supabase/IndexedDB/FileReader',scenarios:report},null,2));console.log(`${report.length} scenarios passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
